# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20171010_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='country',
        ),
    ]
