# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20171010_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.UserData'),
            preserve_default=False,
        ),
    ]
