# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
