# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20171010_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(choices=[('M', 'MAMÁ'), ('P', 'PAPÁ')], max_length=1)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('EV', 'Europa VIP'), ('EL', 'Europa Lujo'), ('ECH', 'Europa Chic'), ('ECHL', 'Europa Chic + Londres'), ('OM', 'Orlando & Miami'), ('OMH', 'Orlando & Miami+Harmony'), ('JCH', 'Japón&China')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('RS', 'Redes Sociales'), ('W', 'Whatsapp'), ('C', 'Correo'), ('L', 'Llamada'), ('F', 'Folleto')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='school',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sourceinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.UserData'),
        ),
        migrations.AddField(
            model_name='programs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.UserData'),
        ),
    ]
