# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20171010_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.UserData'),
            preserve_default=False,
        ),
    ]
